@VideoRent.WebApi_HostAddress = https://localhost:7154

POST {{VideoRent.WebApi_HostAddress}}/api/peliculas/
Content-Type: application/json
Accept: application/json

{
  "peliculaId": 0,
  "titulo": "Inception",
  "subtitulada": true,
  "estreno": false,
  "genero": {
    "generoId": 22,
    "nombreGenero":""
  },
  "actores": [
    {
      "actorId": 45,
      "nombreActor":"",
      "apellidosActor":""
    },
    {
      "actorId": 46,
      "nombreActor":"",
      "apellidosActor":""
    }
  ]
}

###
GET {{VideoRent.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{VideoRent.WebApi_HostAddress}}/api/genero/
Accept: application/json

###
GET {{VideoRent.WebApi_HostAddress}}/api/actors/
Accept: application/json

### Create new actor
POST {{VideoRent.WebApi_HostAddress}}/api/actors/
Content-Type: application/json
Accept: application/json

{
  "actorId": 0,
  "nombreActor": "Tom",
  "apellidosActor": "Hanks"
}

### Update actor
PUT {{VideoRent.WebApi_HostAddress}}/api/actors/45
Content-Type: application/json
Accept: application/json

{
  "actorId": 45,
  "nombreActor": "Keanu",
  "apellidosActor": "Reevesxyz"
}

### Get actor by ID
GET {{VideoRent.WebApi_HostAddress}}/api/actors/45
Accept: application/json

### Delete actor
DELETE {{VideoRent.WebApi_HostAddress}}/api/actors/1
Accept: application/json